# Generated by Django 4.0.1 on 2022-05-11 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_tag_options_alter_bmi_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='intent',
            field=models.CharField(blank=True, choices=[('sleep', 'Sleep'), ('feeding', 'Feeding'), ('pumping', 'Pumping'), ('tummytime', 'TummyTime')], max_length=255, null=True, verbose_name='Intent'),
        ),
    ]
